# -- WHIMC Science Tools --
mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: user
  password: pass
conversions:
  feet:
    expression: "{VAL} * 3.28084"
    unit: "ft"
  fahrenheit:
    expression: "({VAL} * 9.0 / 5.0) + 32.0"
    unit: "°F"
tools:
  ALTITUDE:
    display-name: "altitude"
    default-measurement: "max(0, {Y})"
    unit: "m"
    precision: "4"
    conversions:
      - feet
    worlds:
      world:
        global-measurement: "{Y}"
      world_nether:
        global-measurement: "min(0, {Y} - 128)"
    disabled-worlds:
      - world_the_end
  OXYGEN:
    display-name: "oxygen level"
    default-measurement: "30 + rand(-0.5, 0.5)"
    unit: "%"
    worlds:
      world:
        regions:
          enclosure: "rand(0, 0.1)"
          high_oxygen: "100"
      world_the_end:
        global-measurement: "0"
        regions:
          cage: "10"
          castle: "5"
validation:
  tolerance: 1.0
  timeout: 30
  messages:
    prompt:
      all:
        - '&aWhat value did you measure for &f&l{TOOL}&a?'
        - '&7&oPlease type your answer in chat!'
    timeout:
      all:
        - '&c&lYou failed to tell us a value for {TOOL}! Please try again'
    no-number:
      all:
        - '&cYour message did not contain any numbers!'
    found-number:
      all:
        - 'We found the number ''&7{VAL}&f'' in your message'
    success:
      all:
        - '&a&lGood job!'
        - '&2{VAL} &amatches our calculations!'
    failure:
      all:
        - '&c&lTry again!'
        - '&4{VAL} &cis not quite close enough.'
  commands:
    prompt:
      all:
    timeout:
      all:
    no-number:
      all:
    found-number:
      all:
    success:
      all:
      - 'title {PLAYER} title {"text":"Good job!"}'
