# -- WHIMC Science Tools --
conversions:
  feet:
    expression: "{VAL} * 3.28084"
    unit: "ft"
  fahrenheit:
    expression: "({VAL} * 9.0 / 5.0) + 32.0"
    unit: "°F"
tools:
  ALTITUDE:
    default: "max(0, {Y})"
    unit: "m"
    conversions:
      - feet
    worlds:
      world_nether: "min(0, {Y} - 128)"
    disabled-worlds:
      - "world_the_end"
  OXYGEN:
    default: "30 + rand(-0.5, 0.5)"
    unit: "%"
    regions:
      enclosure: "rand(0, 0.1)"
validation:
  tolerance: 1.0
  timeout: 30
  messages:
    prompt:
      all:
        - '&aWhat value did you measure for &f&l{TOOL}&a?'
        - '&7&oPlease type your answer in chat!'
    timeout:
      all:
        - '&c&lYou failed to tell us a value for {TOOL}! Please try again'
    no-number:
      all:
        - '&cYour message did not contain any numbers!'
    found-number:
      all:
        - 'We found the number ''&7{VAL}&f'' in your message'
    success:
      all:
        - '&a&lGood job!'
        - '&2{VAL} &amatches our calculations!'
    failure:
      all:
        - '&c&lTry again!'
        - '&4{VAL} &cis not quite close enough.'
  commands:
    prompt:
      all:
    timeout:
      all:
    no-number:
      all:
    found-number:
      all:
    success:
      all:
      - 'title {PLAYER} title {"text":"Good job!"}'
